from functools import partial
from albumentations import *



dictInternalAug_brightness_and_transform_settings = {
    "Affine": Affine,
    "AtLeastOneBBoxRandomCrop": AtLeastOneBBoxRandomCrop,
    "BBoxSafeRandomCrop": BBoxSafeRandomCrop,
    "CenterCrop": CenterCrop,
    "CoarseDropout": CoarseDropout,
    "ConstrainedCoarseDropout": ConstrainedCoarseDropout,
    "Crop": Crop,
    "CropAndPad": CropAndPad,
    "CropNonEmptyMaskIfExists": CropNonEmptyMaskIfExists,
    "D4": D4,
    "ElasticTransform": ElasticTransform,
    "Erasing": Erasing,
    "FrequencyMasking": FrequencyMasking,
    "GridDistortion": GridDistortion,
    "GridDropout": GridDropout,
    "GridElasticDeform": GridElasticDeform,
    "HorizontalFlip": HorizontalFlip,
    "LongestMaxSize": LongestMaxSize,
    "MaskDropout": MaskDropout,
    "Morphological": Morphological,
    "NoOp": NoOp,
    "OpticalDistortion": OpticalDistortion,
    "OverlayElements": OverlayElements,
    "Pad": Pad,
    "PadIfNeeded": PadIfNeeded,
    "Perspective": Perspective,
    "PiecewiseAffine": PiecewiseAffine,
    "PixelDropout": PixelDropout,
    "RandomCrop": RandomCrop,
    "RandomCropFromBorders": RandomCropFromBorders,
    "RandomCropNearBBox": RandomCropNearBBox,
    "RandomGridShuffle": RandomGridShuffle,
    "RandomResizedCrop": RandomResizedCrop,
    "RandomRotate90": RandomRotate90,
    "RandomScale": RandomScale,
    "RandomSizedBBoxSafeCrop": RandomSizedBBoxSafeCrop,
    "RandomSizedCrop": RandomSizedCrop,
    "Resize": Resize,
    "Rotate": Rotate,
    "SafeRotate": SafeRotate,
    "ShiftScaleRotate": ShiftScaleRotate,
    "SmallestMaxSize": SmallestMaxSize,
    "ThinPlateSpline": ThinPlateSpline,
    "TimeMasking": TimeMasking,
    "TimeReverse": TimeReverse,
    "Transpose": Transpose,
    "VerticalFlip": VerticalFlip,
    "XYMasking": XYMasking,
    "AdditiveNoise": AdditiveNoise,
    "AdvancedBlur": AdvancedBlur,
    "AutoContrast": AutoContrast,
    "Blur": Blur,
    "CLAHE": CLAHE,
    "ChannelDropout": ChannelDropout,
    "ChannelShuffle": ChannelShuffle,
    "ChromaticAberration": ChromaticAberration,
    "ColorJitter": ColorJitter,
    "Defocus": Defocus,
    "Downscale": Downscale,
    "Emboss": Emboss,
    "Equalize": Equalize,
    "FDA": FDA,
    "FancyPCA": FancyPCA,
    "FromFloat": FromFloat,
    "GaussNoise": GaussNoise,
    "GaussianBlur": GaussianBlur,
    "GlassBlur": GlassBlur,
    "HistogramMatching": HistogramMatching,
    "HueSaturationValue": HueSaturationValue,
    "ISONoise": ISONoise,
    "Illumination": Illumination,
    "ImageCompression": ImageCompression,
    "InvertImg": InvertImg,
    "MedianBlur": MedianBlur,
    "MotionBlur": MotionBlur,
    "MultiplicativeNoise": MultiplicativeNoise,
    "Normalize": Normalize,
    "PixelDistributionAdaptation": PixelDistributionAdaptation,
    "PlanckianJitter": PlanckianJitter,
    "PlasmaBrightnessContrast": PlasmaBrightnessContrast,
    "PlasmaShadow": PlasmaShadow,
    "Posterize": Posterize,
    "RGBShift": RGBShift,
    "RandomBrightnessContrast": RandomBrightnessContrast,
    "RandomFog": RandomFog,
    "RandomGamma": RandomGamma,
    "RandomGravel": RandomGravel,
    "RandomRain": RandomRain,
    "RandomShadow": RandomShadow,
    "RandomSnow": RandomSnow,
    "RandomSunFlare": RandomSunFlare,
    "RandomToneCurve": RandomToneCurve,
    "RingingOvershoot": RingingOvershoot,
    "SaltAndPepper": SaltAndPepper,
    "Sharpen": Sharpen,
    "ShotNoise": ShotNoise,
    "Solarize": Solarize,
    "Spatter": Spatter,
    "Superpixels": Superpixels,
    "TemplateTransform": TemplateTransform,
    "TextImage": TextImage,
    "ToFloat": ToFloat,
    "ToGray": ToGray,
    "ToRGB": ToRGB,
    "ToSepia": ToSepia,
    "UnsharpMask": UnsharpMask,
    "ZoomBlur": ZoomBlur
}

dictInternalAug_brightness_settings = {
    "AdditiveNoise": AdditiveNoise,
    "AdvancedBlur": AdvancedBlur,
    "AutoContrast": AutoContrast,
    "Blur": Blur,
    "CLAHE": CLAHE,
    "ChannelDropout": ChannelDropout,
    "ChannelShuffle": ChannelShuffle,
    "ChromaticAberration": ChromaticAberration,
    "ColorJitter": ColorJitter,
    "Defocus": Defocus,
    "Downscale": Downscale,
    "Emboss": Emboss,
    "Equalize": Equalize,
    "FDA": FDA,
    "FancyPCA": FancyPCA,
    "FromFloat": FromFloat,
    "GaussNoise": GaussNoise,
    "GaussianBlur": GaussianBlur,
    "GlassBlur": GlassBlur,
    "HistogramMatching": HistogramMatching,
    "HueSaturationValue": HueSaturationValue,
    "ISONoise": ISONoise,
    "Illumination": Illumination,
    "ImageCompression": ImageCompression,
    "InvertImg": InvertImg,
    "MedianBlur": MedianBlur,
    "MotionBlur": MotionBlur,
    "MultiplicativeNoise": MultiplicativeNoise,
    "Normalize": Normalize,
    "PixelDistributionAdaptation": PixelDistributionAdaptation,
    "PlanckianJitter": PlanckianJitter,
    "PlasmaBrightnessContrast": PlasmaBrightnessContrast,
    "PlasmaShadow": PlasmaShadow,
    "Posterize": Posterize,
    "RGBShift": RGBShift,
    "RandomBrightnessContrast": RandomBrightnessContrast,
    "RandomFog": RandomFog,
    "RandomGamma": RandomGamma,
    "RandomGravel": RandomGravel,
    "RandomRain": RandomRain,
    "RandomShadow": RandomShadow,
    "RandomSnow": RandomSnow,
    "RandomSunFlare": RandomSunFlare,
    "RandomToneCurve": RandomToneCurve,
    "RingingOvershoot": RingingOvershoot,
    "SaltAndPepper": SaltAndPepper,
    "Sharpen": Sharpen,
    "ShotNoise": ShotNoise,
    "Solarize": Solarize,
    "Spatter": Spatter,
    "Superpixels": Superpixels,
    "TemplateTransform": TemplateTransform,
    "TextImage": TextImage,
    "ToFloat": ToFloat,
    "ToGray": ToGray,
    "ToRGB": ToRGB,
    "ToSepia": ToSepia,
    "UnsharpMask": UnsharpMask,
    "ZoomBlur": ZoomBlur,
}

dictInternalAug_transform_settings = {
    "Affine": Affine,
    "AtLeastOneBBoxRandomCrop": AtLeastOneBBoxRandomCrop,
    "BBoxSafeRandomCrop": BBoxSafeRandomCrop,
    "CenterCrop": CenterCrop,
    "CoarseDropout": CoarseDropout,
    "ConstrainedCoarseDropout": ConstrainedCoarseDropout,
    "Crop": Crop,
    "CropAndPad": CropAndPad,
    "CropNonEmptyMaskIfExists": CropNonEmptyMaskIfExists,
    "D4": D4,
    "ElasticTransform": ElasticTransform,
    "Erasing": Erasing,
    "FrequencyMasking": FrequencyMasking,
    "GridDistortion": GridDistortion,
    "GridDropout": GridDropout,
    "GridElasticDeform": GridElasticDeform,
    "HorizontalFlip": HorizontalFlip,
    "LongestMaxSize": LongestMaxSize,
    "MaskDropout": MaskDropout,
    "Morphological": Morphological,
    "NoOp": NoOp,
    "OpticalDistortion": OpticalDistortion,
    "OverlayElements": OverlayElements,
    "Pad": Pad,
    "PadIfNeeded": PadIfNeeded,
    "Perspective": Perspective,
    "PiecewiseAffine": PiecewiseAffine,
    "PixelDropout": PixelDropout,
    "RandomCrop": RandomCrop,
    "RandomCropFromBorders": RandomCropFromBorders,
    "RandomCropNearBBox": RandomCropNearBBox,
    "RandomGridShuffle": RandomGridShuffle,
    "RandomResizedCrop": RandomResizedCrop,
    "RandomRotate90": RandomRotate90,
    "RandomScale": RandomScale,
    "RandomSizedBBoxSafeCrop": RandomSizedBBoxSafeCrop,
    "RandomSizedCrop": RandomSizedCrop,
    "Resize": Resize,
    "Rotate": Rotate,
    "SafeRotate": SafeRotate,
    "ShiftScaleRotate": ShiftScaleRotate,
    "SmallestMaxSize": SmallestMaxSize,
    "ThinPlateSpline": ThinPlateSpline,
    "TimeMasking": TimeMasking,
    "TimeReverse": TimeReverse,
    "Transpose": Transpose,
    "VerticalFlip": VerticalFlip,
    "XYMasking": XYMasking,
}


dictInternalAug_brightness_settings_через_PARITAL = {
    "AdditiveNoise": partial(AdditiveNoise, p=1),
    "AdvancedBlur": partial(AdvancedBlur, p=1),
    "AutoContrast": partial(AutoContrast, p=1),
    "Blur": partial(Blur, p=1),
    "CLAHE": partial(CLAHE, p=1),
    "ChannelDropout": partial(ChannelDropout, p=1),
    "ChannelShuffle": partial(ChannelShuffle, p=1),
    "ChromaticAberration": partial(ChromaticAberration, p=1),
    "ColorJitter": partial(ColorJitter, p=1),
    "Defocus": partial(Defocus, p=1),
    "Downscale": partial(Downscale, p=1),
    "Emboss": partial(Emboss, p=1),
    "Equalize": partial(Equalize, p=1),
    "FDA": partial(FDA, p=1),
    "FancyPCA": partial(FancyPCA, p=1),
    "FromFloat": partial(FromFloat, p=1),
    "GaussNoise": partial(GaussNoise, p=1),
    "GaussianBlur": partial(GaussianBlur, p=1),
    "GlassBlur": partial(GlassBlur, p=1),
    "HistogramMatching": partial(HistogramMatching, p=1),
    "HueSaturationValue": partial(HueSaturationValue, p=1),
    "ISONoise": partial(ISONoise, p=1),
    "Illumination": partial(Illumination, p=1),
    "ImageCompression": partial(ImageCompression, p=1),
    "InvertImg": partial(InvertImg, p=1),
    "MedianBlur": partial(MedianBlur, p=1),
    "MotionBlur": partial(MotionBlur, p=1),
    "MultiplicativeNoise": partial(MultiplicativeNoise, p=1),
    "Normalize": partial(Normalize, p=1),
    "PixelDistributionAdaptation": partial(PixelDistributionAdaptation, p=1),
    "PlanckianJitter": partial(PlanckianJitter, p=1),
    "PlasmaBrightnessContrast": partial(PlasmaBrightnessContrast, p=1),
    "PlasmaShadow": partial(PlasmaShadow, p=1),
    "Posterize": partial(Posterize, p=1),
    "RGBShift": partial(RGBShift, p=1),
    "RandomBrightnessContrast": partial(RandomBrightnessContrast, p=1),
    "RandomFog": partial(RandomFog, p=1),
    "RandomGamma": partial(RandomGamma, p=1),
    "RandomGravel": partial(RandomGravel, p=1),
    "RandomRain": partial(RandomRain, p=1),
    "RandomShadow": partial(RandomShadow, p=1),
    "RandomSnow": partial(RandomSnow, p=1),
    "RandomSunFlare": partial(RandomSunFlare, p=1),
    "RandomToneCurve": partial(RandomToneCurve, p=1),
    "RingingOvershoot": partial(RingingOvershoot, p=1),
    "SaltAndPepper": partial(SaltAndPepper, p=1),
    "Sharpen": partial(Sharpen, p=1),
    "ShotNoise": partial(ShotNoise, p=1),
    "Solarize": partial(Solarize, p=1),
    "Spatter": partial(Spatter, p=1),
    "Superpixels": partial(Superpixels, p=1),
    "TemplateTransform": partial(TemplateTransform, p=1),
    "TextImage": partial(TextImage, p=1),
    "ToFloat": partial(ToFloat, p=1),
    "ToGray": partial(ToGray, p=1),
    "ToRGB": partial(ToRGB, p=1),
    "ToSepia": partial(ToSepia, p=1),
    "UnsharpMask": partial(UnsharpMask, p=1),
    "ZoomBlur": partial(ZoomBlur, p=1),
}


dictInternalAug_transform_settings_через_parital = {
    "Affine": partial(Affine, p=1),
    "AtLeastOneBBoxRandomCrop": partial(AtLeastOneBBoxRandomCrop, p=1),
    "BBoxSafeRandomCrop": partial(BBoxSafeRandomCrop, p=1),
    "CenterCrop": partial(CenterCrop, p=1),
    "CoarseDropout": partial(CoarseDropout, p=1),
    "ConstrainedCoarseDropout": partial(ConstrainedCoarseDropout, p=1),
    "Crop": partial(Crop, p=1),
    "CropAndPad": partial(CropAndPad, p=1),
    "CropNonEmptyMaskIfExists": partial(CropNonEmptyMaskIfExists, p=1),
    "D4": partial(D4, p=1),
    "ElasticTransform": partial(ElasticTransform, p=1),
    "Erasing": partial(Erasing, p=1),
    "FrequencyMasking": partial(FrequencyMasking, p=1),
    "GridDistortion": partial(GridDistortion, p=1),
    "GridDropout": partial(GridDropout, p=1),
    "GridElasticDeform": partial(GridElasticDeform, p=1),
    "HorizontalFlip": partial(HorizontalFlip, p=1),
    "LongestMaxSize": partial(LongestMaxSize, p=1),
    "MaskDropout": partial(MaskDropout, p=1),
    "Morphological": partial(Morphological, p=1),
    "NoOp": partial(NoOp, p=1),
    "OpticalDistortion": partial(OpticalDistortion, p=1),
    "OverlayElements": partial(OverlayElements, p=1),
    "Pad": partial(Pad, p=1),
    "PadIfNeeded": partial(PadIfNeeded, p=1),
    "Perspective": partial(Perspective, p=1),
    "PiecewiseAffine": partial(PiecewiseAffine, p=1),
    "PixelDropout": partial(PixelDropout, p=1),
    "RandomCrop": partial(RandomCrop, p=1),
    "RandomCropFromBorders": partial(RandomCropFromBorders, p=1),
    "RandomCropNearBBox": partial(RandomCropNearBBox, p=1),
    "RandomGridShuffle": partial(RandomGridShuffle, p=1),
    "RandomResizedCrop": partial(RandomResizedCrop, p=1),
    "RandomRotate90": partial(RandomRotate90, p=1),
    "RandomScale": partial(RandomScale, p=1),
    "RandomSizedBBoxSafeCrop": partial(RandomSizedBBoxSafeCrop, p=1),
    "RandomSizedCrop": partial(RandomSizedCrop, p=1),
    "Resize": partial(Resize, p=1),
    "Rotate": partial(Rotate, p=1),
    "SafeRotate": partial(SafeRotate, p=1),
    "ShiftScaleRotate": partial(ShiftScaleRotate, p=1),
    "SmallestMaxSize": partial(SmallestMaxSize, p=1),
    "ThinPlateSpline": partial(ThinPlateSpline, p=1),
    "TimeMasking": partial(TimeMasking, p=1),
    "TimeReverse": partial(TimeReverse, p=1),
    "Transpose": partial(Transpose, p=1),
    "VerticalFlip": partial(VerticalFlip, p=1),
    "XYMasking": partial(XYMasking, p=1),
}


dictInternalAug_transform_settings_С_ДОПОЛНИТЕЛЬНЫМИ_ПАРАМЕТРАМИ = {
    "Affine": partial(Affine, scale=(0.5, 1.5), translate_percent=(0.1, 0.1), rotate=(-45, 45), shear=(-16, 16), p=1.0),
    "AtLeastOneBBoxRandomCrop": partial(AtLeastOneBBoxRandomCrop, p=1.0),
    "BBoxSafeRandomCrop": partial(BBoxSafeRandomCrop, p=1.0),
    "CenterCrop": partial(CenterCrop, height=256, width=256, p=1.0),
    "CoarseDropout": partial(CoarseDropout, max_holes=8, max_height=8, max_width=8, min_holes=1, p=1.0),
    "ConstrainedCoarseDropout": partial(ConstrainedCoarseDropout, max_holes=8, max_height=8, max_width=8, min_holes=1, p=1.0),
    "Crop": partial(Crop, x_min=0, y_min=0, x_max=256, y_max=256, p=1.0),
    "CropAndPad": partial(CropAndPad, top=10, left=10, height=256, width=256, p=1.0),
    "CropNonEmptyMaskIfExists": partial(CropNonEmptyMaskIfExists, p=1.0),
    "D4": partial(D4, p=1.0),
    "ElasticTransform": partial(ElasticTransform, alpha=1.0, sigma=50, p=1.0),
    "Erasing": partial(Erasing, p=1.0),
    "FrequencyMasking": partial(FrequencyMasking, p=1.0),
    "GridDistortion": partial(GridDistortion, num_steps=5, distort_limit=0.3, p=1.0),
    "GridDropout": partial(GridDropout, p=1.0),
    "GridElasticDeform": partial(GridElasticDeform, num_grid_xy=(5, 5), magnitude=10, p=1.0),
    "HorizontalFlip": partial(HorizontalFlip, p=1.0),
    "LongestMaxSize": partial(LongestMaxSize, max_size=256, p=1.0),
    "MaskDropout": partial(MaskDropout, p=1.0),
    "Morphological": partial(Morphological, p=1.0),
    "NoOp": partial(NoOp, p=1.0),
    "OpticalDistortion": partial(OpticalDistortion, distort_limit=0.5, shift_limit=0.5, p=1.0),
    "OverlayElements": partial(OverlayElements, p=1.0),
    "Pad": partial(Pad, border_mode=0, p=1.0),
    "PadIfNeeded": partial(PadIfNeeded, min_height=256, min_width=256, p=1.0),
    "Perspective": partial(Perspective, scale=(0.05, 0.1), p=1.0),
    "PiecewiseAffine": partial(PiecewiseAffine, scale=0.05, p=1.0),
    "PixelDropout": partial(PixelDropout, p=1.0),
    "RandomCrop": partial(RandomCrop, height=640, width=2640, p=1.0),
    "RandomCropFromBorders": partial(RandomCropFromBorders, p=1.0),
    "RandomCropNearBBox": partial(RandomCropNearBBox, p=1.0),
    "RandomGridShuffle": partial(RandomGridShuffle, p=1.0),
    "RandomResizedCrop": partial(RandomResizedCrop, height=640, width=640, p=1.0),
    "RandomRotate90": partial(RandomRotate90, p=1.0),
    "RandomScale": partial(RandomScale, scale_limit=0.1, p=1.0),
    "RandomSizedBBoxSafeCrop": partial(RandomSizedBBoxSafeCrop, height=256, width=256, p=1.0),
    "RandomSizedCrop": partial(RandomSizedCrop, min_max_height=(256, 512), height=256, p=1.0),
    "Resize": partial(Resize, height=256, width=256, p=1.0),
    "Rotate": partial(Rotate, limit=360, p=1.0),
    "SafeRotate": partial(SafeRotate, limit=45, p=1.0),
    "ShiftScaleRotate": partial(ShiftScaleRotate, shift_limit=0.0625, scale_limit=0.1, rotate_limit=45, p=1.0),
    "SmallestMaxSize": partial(SmallestMaxSize, max_size=256, p=1.0),
    "ThinPlateSpline": partial(ThinPlateSpline, p=1.0),
    "TimeMasking": partial(TimeMasking, p=1.0),
    "TimeReverse": partial(TimeReverse, p=1.0),
    "Transpose": partial(Transpose, p=1.0),
    "VerticalFlip": partial(VerticalFlip, p=1.0),
    "XYMasking": partial(XYMasking, p=1.0),
}





# в это ловаре смотри внимательно параметры, они указаны не правильно...
dictParamsAug_Yolo = {
    "epochs": [1, 2, 5, 10, 20, 50, 100],  # Количество эпох
    "batch_size": [1, 2, 4, 8, 16, 32, 64],  # Размер батча
    "learning_rate": [0.001, 0.01, 0.1, 0.0001],  # Скорость обучения
    "img_size": [320, 416, 512, 608, 640],  # Размер изображения
    "data_augmentation": [True, False],  # Использовать ли аугментацию данных
    "optimizer": ["SGD", "Adam", "RMSprop"],  # Оптимизатор
    "momentum": [0.0, 0.5, 0.9, 0.99],  # Моментум для SGD
    "weight_decay": [0.0, 0.0001, 0.001],  # Регуляризация L2
    "pretrained": [True, False],  # Использовать ли предобученные веса
    "checkpoint": [True, False],  # Сохранять ли контрольные точки
    "class_names": ["coco", "custom"],  # Названия классов

    # Параметры аугментации
    "flip": [True, False],  # Отражение изображения по горизонтали
    "rotate": [i for i in range(0,361, 12)],  # Угол поворота изображения
    "scale": [0.5, 1.0, 1.5, 2.0],  # Масштабирование изображения
    "translate": [0, 10, 20],  # Сдвиг изображения по осям
    "brightness": [0.0, 0.5, 1.0, 1.5],  # Яркость изображения
    "contrast": [0.0, 0.5, 1.0, 1.5],  # Контрастность изображения
    "saturation": [0.0, 0.5, 1.0, 1.5],  # Насыщенность изображения
    "hue": [-0.1, 0.0, 0.1],  # Оттенок изображения
}