from functools import partial
from albumentations import *
import cv2




#Используется для запуска функций с необходимыми параметрами
dictInternalAug_brightness_and_transform_settings = { 
    "AtLeastOneBBoxRandomCrop": partial(AtLeastOneBBoxRandomCrop, **{"height": 640, "width": 640} ), 
    "CropAndPad": partial(CropAndPad, **{"percent":0}),
    "GridElasticDeform": partial(GridElasticDeform, **{"num_grid_xy": (8,10), "magnitude": 10}),
    "LongestMaxSize": partial(LongestMaxSize, **{"max_size_hw": (640, 640)}),
    "RandomCrop": partial(RandomCrop, **{"height": 640, "width": 640}),
    "Resize": partial(Resize, **{"height": 640, "width": 640}),
    "Rotate": partial(Rotate, **{"limit": (13,340), "border_mode": cv2.BORDER_REFLECT,}),
    "RandomRotate90": RandomRotate90,
    "Affine": Affine,
    "BBoxSafeRandomCrop": BBoxSafeRandomCrop,
    "CoarseDropout": CoarseDropout,
    "ConstrainedCoarseDropout": ConstrainedCoarseDropout,
    #"Crop": Crop,
    "D4": D4,
    "ElasticTransform": ElasticTransform,
    "Erasing": Erasing,
    "FrequencyMasking": FrequencyMasking,
    "GridDistortion": GridDistortion,
    "GridDropout": GridDropout,
    "HorizontalFlip": HorizontalFlip,
    "MaskDropout": MaskDropout,
    #"NoOp": NoOp,
    "OpticalDistortion": OpticalDistortion,
    "OverlayElements": OverlayElements,
    "Pad": Pad,
    "PadIfNeeded": PadIfNeeded,
    "Perspective": Perspective,
    "PiecewiseAffine": PiecewiseAffine,
    #"PixelDropout": PixelDropout,
    "RandomCropFromBorders": RandomCropFromBorders,
    "RandomCropNearBBox": RandomCropNearBBox,
    "RandomGridShuffle": RandomGridShuffle,
    "RandomResizedCrop": RandomResizedCrop,
    "RandomScale": RandomScale,
    "RandomSizedBBoxSafeCrop": RandomSizedBBoxSafeCrop,
    "RandomSizedCrop": RandomSizedCrop,
    "SafeRotate": SafeRotate,
    "ShiftScaleRotate": ShiftScaleRotate,
    "SmallestMaxSize": SmallestMaxSize,
    "ThinPlateSpline": ThinPlateSpline,
    #"TimeMasking": TimeMasking,
    #"TimeReverse": TimeReverse,
    "Transpose": Transpose,
    "VerticalFlip": VerticalFlip,
    "XYMasking": XYMasking,
    "AdditiveNoise": AdditiveNoise,
    "AdvancedBlur": AdvancedBlur,
    "AutoContrast": AutoContrast,
    "Blur": Blur,
    "CLAHE": CLAHE,
    "ChannelDropout": ChannelDropout,
    "ChannelShuffle": ChannelShuffle,
    "ChromaticAberration": ChromaticAberration,
    "ColorJitter": ColorJitter,
    "Defocus": Defocus,
    "Downscale": Downscale,
    "Emboss": Emboss,
    "Equalize": Equalize,
    "FancyPCA": FancyPCA,
    "FromFloat": FromFloat,
    "GaussNoise": GaussNoise,
    "GaussianBlur": GaussianBlur,
    "GlassBlur": GlassBlur,
    "HueSaturationValue": HueSaturationValue,
    "ISONoise": ISONoise,
    "Illumination": Illumination,
    "ImageCompression": ImageCompression,
    "InvertImg": InvertImg,
    "MedianBlur": MedianBlur,
    "MotionBlur": MotionBlur,
    "MultiplicativeNoise": MultiplicativeNoise,
    "Normalize": Normalize,
    "PlanckianJitter": PlanckianJitter,
    "PlasmaBrightnessContrast": PlasmaBrightnessContrast,
    "PlasmaShadow": PlasmaShadow,
    "Posterize": Posterize,
    "RGBShift": RGBShift,
    "RandomBrightnessContrast": RandomBrightnessContrast,
    "RandomFog": RandomFog,
    "RandomGamma": RandomGamma,
    "RandomGravel": RandomGravel,
    "RandomRain": RandomRain,
    "RandomShadow": RandomShadow,
    "RandomSnow": RandomSnow,
    "RandomSunFlare": RandomSunFlare,
    "RandomToneCurve": RandomToneCurve,
    "RingingOvershoot": RingingOvershoot,
    "SaltAndPepper": SaltAndPepper,
    "Sharpen": Sharpen,
    "ShotNoise": ShotNoise,
    "Solarize": Solarize,
    "Spatter": Spatter,
    "Superpixels": Superpixels,
    "ToFloat": ToFloat,
    "ToGray": ToGray,
    "ToRGB": ToRGB,
    "ToSepia": ToSepia,
    "UnsharpMask": UnsharpMask,
    "ZoomBlur": ZoomBlur
}

#Используется для вывода методов изменения яркости
dictInternalAug_brightness_settings = { 
    "AdditiveNoise": AdditiveNoise,
    #"AdvancedBlur": AdvancedBlur,
    "AutoContrast": AutoContrast,
    "Blur": Blur,
    "CLAHE": CLAHE,
    "ChannelDropout": ChannelDropout,
    "ChannelShuffle": ChannelShuffle,
    "ChromaticAberration": ChromaticAberration,
    "ColorJitter": ColorJitter,
    "Defocus": Defocus,
    "Downscale": Downscale,
    "Emboss": Emboss,
    "Equalize": Equalize,
    #"FancyPCA": FancyPCA,
    "FromFloat": FromFloat,
    "GaussNoise": GaussNoise,
    "GaussianBlur": GaussianBlur,
    "GlassBlur": GlassBlur,
    "HueSaturationValue": HueSaturationValue,
    "ISONoise": ISONoise,
    "Illumination": Illumination,
    #"ImageCompression": ImageCompression,
    "InvertImg": InvertImg,
    "MedianBlur": MedianBlur,
    "MotionBlur": MotionBlur,
    "MultiplicativeNoise": MultiplicativeNoise,
    #"Normalize": Normalize,
    "PlanckianJitter": PlanckianJitter,
    "PlasmaBrightnessContrast": PlasmaBrightnessContrast,
    "PlasmaShadow": PlasmaShadow,
    "Posterize": Posterize,
    "RGBShift": RGBShift,
    "RandomBrightnessContrast": RandomBrightnessContrast,
    "RandomFog": RandomFog,
    "RandomGamma": RandomGamma,
    "RandomGravel": RandomGravel,
    "RandomRain": RandomRain,
    "RandomShadow": RandomShadow,
    "RandomSnow": RandomSnow,
    "RandomSunFlare": RandomSunFlare,
    "RandomToneCurve": RandomToneCurve,
    #"RingingOvershoot": RingingOvershoot,
    "SaltAndPepper": SaltAndPepper,
    "Sharpen": Sharpen,
    "ShotNoise": ShotNoise,
    "Solarize": Solarize,
    "Spatter": Spatter,
    "Superpixels": Superpixels,
    #"ToFloat": ToFloat,
    "ToGray": ToGray,
    #"ToRGB": ToRGB,
    "ToSepia": ToSepia,
    #"UnsharpMask": UnsharpMask,
    "ZoomBlur": ZoomBlur
}

#Используется для вывода методов трансформации
dictInternalAug_transform_settings = { 
    "AtLeastOneBBoxRandomCrop": AtLeastOneBBoxRandomCrop,
    "CropAndPad": CropAndPad,
    "GridElasticDeform": GridElasticDeform,
    "LongestMaxSize": LongestMaxSize,
    "RandomCrop": RandomCrop,
    "RandomRotate90": RandomRotate90,
    "Resize": Resize,
    "Rotate": Rotate,
    "Affine": Affine,
    "BBoxSafeRandomCrop": BBoxSafeRandomCrop,
    "CoarseDropout": CoarseDropout,
    "ConstrainedCoarseDropout": ConstrainedCoarseDropout,
    #"Crop": Crop,
    "D4": D4,
    "ElasticTransform": ElasticTransform,
    "Erasing": Erasing,
    "FrequencyMasking": FrequencyMasking,
    "GridDistortion": GridDistortion,
    "GridDropout": GridDropout,
    "HorizontalFlip": HorizontalFlip,
    "LongestMaxSize": LongestMaxSize,
    #"NoOp": NoOp,
    "OpticalDistortion": OpticalDistortion,
    "Pad": Pad,
    "Perspective": Perspective,
    #"PixelDropout": PixelDropout,
    "RandomCrop": RandomCrop,
    "RandomRotate90": RandomRotate90,
    "Resize": Resize,
    "Rotate": Rotate,
    "ThinPlateSpline": ThinPlateSpline,
    #"TimeMasking": TimeMasking,
    #"TimeReverse": TimeReverse,
    "Transpose": Transpose,
    "VerticalFlip": VerticalFlip
}

dictParamsAug_Yolo = {
    "hsv_h": 0.015,  
    "hsv_s": 0.7,  
    "hsv_v": 0.4,  
    "degrees": 0.0,  
    "translate": 0.1, 
    "scale": 0.5, 
    "shear": 0.0, 
    "perspective": 0.001, 
    "flipud": 0.0,  
    "fliplr": 0.5, 
    "bgr": 0.0, 
    "mosaic": 1.0, 
    "mixup": 0.0,  
    "copy_paste": 0.0,  
    "copy_paste_mode": "flip",  
    "auto_augment": "randaugment",  
    "erasing": 0.4,  
    "crop_fraction": 1.0,  
}

