from functools import partial
from albumentations import *
import cv2
# Тут будет импорт yaml файла с параметрами

#В yaml файле будем хранить парметры, при вызове какой-то настройки будем пересохранять этот файл
#А в словаре  через partial argfun = парметр ипортированный из yaml
#Осталоьс только найти дурака который все это напишет! Ах да он напртив монитора)0))00)
#Там где будут списки - будет выпадать список, все остальное вводится через QLineEdit
#После нажтия ok парметры переcохраняются в yaml



dictInternalAug_brightness_and_transform_settings = {
    "Affine": Affine, 
    "AtLeastOneBBoxRandomCrop": AtLeastOneBBoxRandomCrop,
    "BBoxSafeRandomCrop": BBoxSafeRandomCrop,
    "CenterCrop": CenterCrop,
    "CoarseDropout": CoarseDropout,
    "ConstrainedCoarseDropout": ConstrainedCoarseDropout,
    "Crop": Crop,
    "CropAndPad": CropAndPad,
    "CropNonEmptyMaskIfExists": CropNonEmptyMaskIfExists,
    "D4": D4,
    "ElasticTransform": ElasticTransform,
    "Erasing": Erasing,
    "FrequencyMasking": FrequencyMasking,
    "GridDistortion": GridDistortion,
    "GridDropout": GridDropout,
    "GridElasticDeform": GridElasticDeform,
    "HorizontalFlip": HorizontalFlip,
    "LongestMaxSize": LongestMaxSize,
    "MaskDropout": MaskDropout,
    "Morphological": Morphological,
    "NoOp": NoOp,
    "OpticalDistortion": OpticalDistortion,
    "OverlayElements": OverlayElements,
    "Pad": Pad,
    "PadIfNeeded": PadIfNeeded,
    "Perspective": Perspective,
    "PiecewiseAffine": PiecewiseAffine,
    "PixelDropout": PixelDropout,
    "RandomCrop": RandomCrop,
    "RandomCropFromBorders": RandomCropFromBorders,
    "RandomCropNearBBox": RandomCropNearBBox,
    "RandomGridShuffle": RandomGridShuffle,
    "RandomResizedCrop": RandomResizedCrop,
    "RandomRotate90": RandomRotate90,
    "RandomScale": RandomScale,
    "RandomSizedBBoxSafeCrop": RandomSizedBBoxSafeCrop,
    "RandomSizedCrop": RandomSizedCrop,
    "Resize": Resize,
    "Rotate": Rotate,
    "SafeRotate": SafeRotate,
    "ShiftScaleRotate": ShiftScaleRotate,
    "SmallestMaxSize": SmallestMaxSize,
    "ThinPlateSpline": ThinPlateSpline,
    "TimeMasking": TimeMasking,
    "TimeReverse": TimeReverse,
    "Transpose": Transpose,
    "VerticalFlip": VerticalFlip,
    "XYMasking": XYMasking,
    "AdditiveNoise": AdditiveNoise,
    "AdvancedBlur": AdvancedBlur,
    "AutoContrast": AutoContrast,
    "Blur": Blur,
    "CLAHE": CLAHE,
    "ChannelDropout": ChannelDropout,
    "ChannelShuffle": ChannelShuffle,
    "ChromaticAberration": ChromaticAberration,
    "ColorJitter": ColorJitter,
    "Defocus": Defocus,
    "Downscale": Downscale,
    "Emboss": Emboss,
    "Equalize": Equalize,
    "FDA": FDA,
    "FancyPCA": FancyPCA,
    "FromFloat": FromFloat,
    "GaussNoise": GaussNoise,
    "GaussianBlur": GaussianBlur,
    "GlassBlur": GlassBlur,
    "HistogramMatching": HistogramMatching,
    "HueSaturationValue": HueSaturationValue,
    "ISONoise": ISONoise,
    "Illumination": Illumination,
    "ImageCompression": ImageCompression,
    "InvertImg": InvertImg,
    "MedianBlur": MedianBlur,
    "MotionBlur": MotionBlur,
    "MultiplicativeNoise": MultiplicativeNoise,
    "Normalize": Normalize,
    "PixelDistributionAdaptation": PixelDistributionAdaptation,
    "PlanckianJitter": PlanckianJitter,
    "PlasmaBrightnessContrast": PlasmaBrightnessContrast,
    "PlasmaShadow": PlasmaShadow,
    "Posterize": Posterize,
    "RGBShift": RGBShift,
    "RandomBrightnessContrast": RandomBrightnessContrast,
    "RandomFog": RandomFog,
    "RandomGamma": RandomGamma,
    "RandomGravel": RandomGravel,
    "RandomRain": RandomRain,
    "RandomShadow": RandomShadow,
    "RandomSnow": RandomSnow,
    "RandomSunFlare": RandomSunFlare,
    "RandomToneCurve": RandomToneCurve,
    "RingingOvershoot": RingingOvershoot,
    "SaltAndPepper": SaltAndPepper,
    "Sharpen": Sharpen,
    "ShotNoise": ShotNoise,
    "Solarize": Solarize,
    "Spatter": Spatter,
    "Superpixels": Superpixels,
    "TemplateTransform": TemplateTransform,
    "TextImage": TextImage,
    "ToFloat": ToFloat,
    "ToGray": ToGray,
    "ToRGB": ToRGB,
    "ToSepia": ToSepia,
    "UnsharpMask": UnsharpMask,
    "ZoomBlur": ZoomBlur
}

dictInternalAug_brightness_settings = {
    "AdditiveNoise": AdditiveNoise,
    "AdvancedBlur": AdvancedBlur,
    "AutoContrast": AutoContrast,
    "Blur": Blur,
    "CLAHE": CLAHE,
    "ChannelDropout": ChannelDropout,
    "ChannelShuffle": ChannelShuffle,
    "ChromaticAberration": ChromaticAberration,
    "ColorJitter": ColorJitter,
    "Defocus": Defocus,
    "Downscale": Downscale,
    "Emboss": Emboss,
    "Equalize": Equalize,
    "FDA": FDA,
    "FancyPCA": FancyPCA,
    "FromFloat": FromFloat,
    "GaussNoise": GaussNoise,
    "GaussianBlur": GaussianBlur,
    "GlassBlur": GlassBlur,
    "HistogramMatching": HistogramMatching,
    "HueSaturationValue": HueSaturationValue,
    "ISONoise": ISONoise,
    "Illumination": Illumination,
    "ImageCompression": ImageCompression,
    "InvertImg": InvertImg,
    "MedianBlur": MedianBlur,
    "MotionBlur": MotionBlur,
    "MultiplicativeNoise": MultiplicativeNoise,
    "Normalize": Normalize,
    "PixelDistributionAdaptation": PixelDistributionAdaptation,
    "PlanckianJitter": PlanckianJitter,
    "PlasmaBrightnessContrast": PlasmaBrightnessContrast,
    "PlasmaShadow": PlasmaShadow,
    "Posterize": Posterize,
    "RGBShift": RGBShift,
    "RandomBrightnessContrast": RandomBrightnessContrast,
    "RandomFog": RandomFog,
    "RandomGamma": RandomGamma,
    "RandomGravel": RandomGravel,
    "RandomRain": RandomRain,
    "RandomShadow": RandomShadow,
    "RandomSnow": RandomSnow,
    "RandomSunFlare": RandomSunFlare,
    "RandomToneCurve": RandomToneCurve,
    "RingingOvershoot": RingingOvershoot,
    "SaltAndPepper": SaltAndPepper,
    "Sharpen": Sharpen,
    "ShotNoise": ShotNoise,
    "Solarize": Solarize,
    "Spatter": Spatter,
    "Superpixels": Superpixels,
    "TemplateTransform": TemplateTransform,
    "TextImage": TextImage,
    "ToFloat": ToFloat,
    "ToGray": ToGray,
    "ToRGB": ToRGB,
    "ToSepia": ToSepia,
    "UnsharpMask": UnsharpMask,
    "ZoomBlur": ZoomBlur,
}
# делаем словарь ерез partial(fun, arg1 = funarg1, arg2 = funarg2)
dictInternalAug_transform_settings = {
    "Affine": Affine,
    "AtLeastOneBBoxRandomCrop": AtLeastOneBBoxRandomCrop,
    "BBoxSafeRandomCrop": BBoxSafeRandomCrop,
    "CenterCrop": CenterCrop,
    "CoarseDropout": CoarseDropout,
    "ConstrainedCoarseDropout": ConstrainedCoarseDropout,
    "Crop": Crop,
    "CropAndPad": CropAndPad,
    "CropNonEmptyMaskIfExists": CropNonEmptyMaskIfExists,
    "D4": D4,
    "ElasticTransform": ElasticTransform,
    "Erasing": Erasing,
    "FrequencyMasking": FrequencyMasking,
    "GridDistortion": GridDistortion,
    "GridDropout": GridDropout,
    "GridElasticDeform": GridElasticDeform,
    "HorizontalFlip": HorizontalFlip,
    "LongestMaxSize": LongestMaxSize,
    "MaskDropout": MaskDropout,
    "Morphological": Morphological,
    "NoOp": NoOp,
    "OpticalDistortion": OpticalDistortion,
    "Pad": Pad,
    "PadIfNeeded": PadIfNeeded,
    "Perspective": Perspective,
    "PiecewiseAffine": PiecewiseAffine,
    "PixelDropout": PixelDropout,
    "RandomCrop": RandomCrop,
    "RandomCropFromBorders": RandomCropFromBorders,
    "RandomCropNearBBox": RandomCropNearBBox,
    "RandomGridShuffle": RandomGridShuffle,
    "RandomResizedCrop": RandomResizedCrop,
    "RandomRotate90": RandomRotate90,
    "RandomScale": RandomScale,
    "RandomSizedBBoxSafeCrop": RandomSizedBBoxSafeCrop,
    "RandomSizedCrop": RandomSizedCrop,
    "Resize": Resize,
    "Rotate": Rotate,
    "SafeRotate": SafeRotate,
    "ShiftScaleRotate": ShiftScaleRotate,
    "SmallestMaxSize": SmallestMaxSize,
    "ThinPlateSpline": ThinPlateSpline,
    "TimeMasking": TimeMasking,
    "TimeReverse": TimeReverse,
    "Transpose": Transpose,
    "VerticalFlip": VerticalFlip,
    "XYMasking": XYMasking,
}



# в это ловаре смотри внимательно параметры, они указаны не правильно...
dictParamsAug_Yolo = {
    "epochs": [1, 2, 5, 10, 20, 50, 100],  # Количество эпох
    "batch_size": [1, 2, 4, 8, 16, 32, 64],  # Размер батча
    "learning_rate": [0.001, 0.01, 0.1, 0.0001],  # Скорость обучения
    "img_size": [320, 416, 512, 608, 640],  # Размер изображения
    "data_augmentation": [True, False],  # Использовать ли аугментацию данных
    "optimizer": ["SGD", "Adam", "RMSprop"],  # Оптимизатор
    "momentum": [0.0, 0.5, 0.9, 0.99],  # Моментум для SGD
    "weight_decay": [0.0, 0.0001, 0.001],  # Регуляризация L2
    "pretrained": [True, False],  # Использовать ли предобученные веса
    "checkpoint": [True, False],  # Сохранять ли контрольные точки
    "class_names": ["coco", "custom"],  # Названия классов

    # Параметры аугментации
    "flip": [True, False],  # Отражение изображения по горизонтали
    "rotate": [i for i in range(0,361, 12)],  # Угол поворота изображения
    "scale": [0.5, 1.0, 1.5, 2.0],  # Масштабирование изображения
    "translate": [0, 10, 20],  # Сдвиг изображения по осям
    "brightness": [0.0, 0.5, 1.0, 1.5],  # Яркость изображения
    "contrast": [0.0, 0.5, 1.0, 1.5],  # Контрастность изображения
    "saturation": [0.0, 0.5, 1.0, 1.5],  # Насыщенность изображения
    "hue": [-0.1, 0.0, 0.1],  # Оттенок изображения
}